bar:
  left:
    - dwl:
      number-of-tags: 9
      dwl-info-filename: "~/.cache/dwl_info"
      name-of-tags: [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
      content:
        list:
          items:
            - map:
              conditions:
              # default tag
              id == 0: {string: {text: "{layout} {title}"}}
              selected: {string: {text: "-> {name}"}}
              ~empty: {string: {text: "{name}"}}
              urgent: {string: {text: "=> {name} <="}}

  right:
    - clock:
      date-format: "%d %b"
      time-format: "%H:%M"
      content:
        string: {text: "{date} {time}"}
